name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: sudo ./gradlew build
    - name: Add Credentials-Username
      run: git config --global user.name "YonghoAhn"
    - name: Add Credentials-Email
      run: git config --global user.email "hrh1110@naver.com"
    - name: Debug APK Publisher
      uses: ShaunLWM/action-release-debugapk@0.0.5
